version: "3.8"

services:
    nginx:
        image: "nginx:stable-alpine"
        restart: unless-stopped
        ports:
            - "7070:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/tbc
        depends_on:
            - php
            - mysql
        networks:
            - tbc-global
            - tbc-local
    php:
        build:
            context: .
            dockerfile: docker/dockerfiles/php.Dockerfile
            args:
                - CACHEBUST:$(date +%s)
        restart: unless-stopped
        volumes:
            - ./:/var/www/tbc
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - tbc-global
            - tbc-local
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        env_file:
            - docker/env/mysql.env
        networks:
            - tbc-global
            - tbc-local
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "9090:80"
        env_file:
            - docker/env/mysql.env
        volumes:
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
            - mysql
        networks:
            - tbc-global
            - tbc-local

networks:
    tbc-global:
        name: tbc-global
        driver: bridge
    tbc-local:
        name: tbc-local
        driver: bridge
